### ISSUE TITLE
failed to run  run_alphafold.sh 

### ISSUE THREAD

**Issue by dorothyzh** [v-mikhaylov/tfold-full#1]
(tfold-env) root@huan-ubuntu:/opt/app/ezhpc/alphafold/2.3.2/tfold-release# sh model_pmhcs.sh /home/ubuntu/test.csv ./test2
MHC loading from MHC.pckl. To update the pickle file, set use_pickle to False
loaded 26122 MHC sequences in  0.6 s
2024-03-01 15:57:47.562538: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Need to model 1 pMHCs.
Retrieving MHC objects from alleles.
making Kd predictions for 1 pmhcs...
2024-03-01 15:57:48.129942: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-03-01 15:57:48.156868: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-03-01 15:57:48.156887: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (huan-ubuntu): /proc/driver/nvidia/version does not exist
2024-03-01 15:57:48.157061: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/opt/app/ezhpc/conda/envs/tfold-env/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:588: UserWarning: Input dict contained keys ['regmask', 'tails'] which did not match any model input. They will be ignored by the model.
  warnings.warn(
total AF models to be produced: 10
2024-03-01 15:57:55.793097: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0301 15:57:56.351333 139983118890816 tfold_run_alphafold.py:151] processing 10 inputs...
I0301 15:57:56.454113 139983118890816 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker:
2024-03-01 15:57:56.474424: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0301 15:57:56.474539 139983118890816 xla_bridge.py:231] Unable to initialize backend 'gpu': Failed precondition: No visible GPU devices.
I0301 15:57:56.474767 139983118890816 xla_bridge.py:231] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
W0301 15:57:56.474810 139983118890816 xla_bridge.py:236] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I0301 15:57:57.247613 139983118890816 tfold_run_alphafold.py:172] Have 1 models: ['model_1']
I0301 15:57:57.247697 139983118890816 tfold_run_alphafold.py:176] Using random seed 6214715378330762611 for the data pipeline
I0301 15:57:57.247793 139983118890816 tfold_run_alphafold.py:87] Predicting for id 0
Traceback (most recent call last):
  File "tfold_run_alphafold.py", line 196, in <module>
    app.run(main)
  File "/opt/app/ezhpc/conda/envs/tfold-env/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/app/ezhpc/conda/envs/tfold-env/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "tfold_run_alphafold.py", line 186, in main
    predict_structure(sequences=sequences,msas=msas,template_hits=template_hits,renumber_list=renumber_list,
  File "tfold_run_alphafold.py", line 92, in predict_structure
    feature_dict=data_pipeline.process(sequences,msas,template_hits)
  File "/opt/app/ezhpc/alphafold/2.3.2/tfold-release/tfold_patch/tfold_pipeline.py", line 135, in process
    msa_features=make_msa_features(msas)
  File "/opt/app/ezhpc/alphafold/2.3.2/tfold-release/tfold_patch/tfold_pipeline.py", line 113, in make_msa_features
    uniprot_accession_ids.append(identifiers.uniprot_accession_id.encode('utf-8'))
AttributeError: 'Identifiers' object has no attribute 'uniprot_accession_id'
Traceback (most recent call last):
  File "collect_results.py", line 12, in <module>
    result_parse_tools.parse_results(working_dir)
  File "/opt/app/ezhpc/alphafold/2.3.2/tfold-release/tfold/modeling/result_parse_tools.py", line 74, in parse_results
    if get_rmsd:
UnboundLocalError: local variable 'get_rmsd' referenced before assignment

**Comment by v-mikhaylov** [comment]
Hi! Please use release from here: `https://github.com/v-mikhaylov/tfold-release/tree/main` with AlphaFold version 2.1. If the issue persists, double check that AlphaFold is able to use the CUDA GPU device.

**Comment by dorothyzh** [comment]
So the tfold can only support alphafold 2.1 rather than 2.3? And how to check the alphafold usage on CUDA GPU
